export const ADD_MOVIE_INIT = 'ADD_MOVIE_INIT';
export const ADD_MOVIE_SUCCESS = 'ADD_MOVIE_SUCCESS';
export const ADD_MOVIE_FAIL = 'ADD_MOVIE_FAIL';

export const GET_MOVIE_INIT = 'GET_MOVIE_INIT';
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
export const GET_MOVIE_FAIL = 'GET_MOVIE_FAIL';

export const GET_MOVIE_BY_ID_INIT = 'GET_MOVIE_BY_ID_INIT';
export const GET_MOVIE_BY_ID_SUCCESS = 'GET_MOVIE_BY_ID_SUCCESS';
export const GET_MOVIE_BY_ID_FAIL = 'GET_MOVIE_BY_ID_FAIL';

export const UPDATE_MOVIE_INIT = 'UPDATE_MOVIE_INIT';
export const UPDATE_MOVIE_SUCCESS = 'UPDATE_MOVIE_SUCCESS';
export const UPDATE_MOVIE_FAIL = 'UPDATE_MOVIE_FAIL';

export const DELETE_MOVIE_INIT = 'DELETE_MOVIE_INIT';
export const DELETE_MOVIE_SUCCESS = 'DELETE_MOVIE_SUCCESS';
export const DELETE_MOVIE_FAIL = 'DELETE_MOVIE_FAIL';
