export const ADD_TIME_INIT = 'ADD_TIME_INIT';
export const ADD_TIME_SUCCESS = 'ADD_TIME_SUCCESS';
export const ADD_TIME_FAIL = 'ADD_TIME_FAIL';

export const GET_TIME_INIT = 'GET_TIME_INIT';
export const GET_TIME_SUCCESS = 'GET_TIME_SUCCESS';
export const GET_TIME_FAIL = 'GET_TIME_FAIL';

export const UPDATE_TIME_INIT = 'UPDATE_TIME_INIT';
export const UPDATE_TIME_SUCCESS = 'UPDATE_TIME_SUCCESS';
export const UPDATE_TIME_FAIL = 'UPDATE_TIME_FAIL';

export const DELETE_TIME_INIT = 'DELETE_TIME_INIT';
export const DELETE_TIME_SUCCESS = 'DELETE_TIME_SUCCESS';
export const DELETE_TIME_FAIL = 'DELETE_TIME_FAIL';
